/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JCovPCG_PCGuidance */

#ifndef _Included_JCovPCG_PCGuidance
#define _Included_JCovPCG_PCGuidance
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JCovPCG_PCGuidance
 * Method:    pcgCFGAlloct
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_JCovPCG_PCGuidance_pcgCFGAlloct
  (JNIEnv *, jclass, jint);

/*
 * Class:     JCovPCG_PCGuidance
 * Method:    pcgCFGEdge
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_JCovPCG_PCGuidance_pcgCFGEdge
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     JCovPCG_PCGuidance
 * Method:    pcgBuild
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JCovPCG_PCGuidance_pcgBuild
  (JNIEnv *, jclass);

/*
 * Class:     JCovPCG_PCGuidance
 * Method:    pcgNeedInstrumented
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_JCovPCG_PCGuidance_pcgNeedInstrumented
  (JNIEnv *, jclass, jint);

/*
 * Class:     JCovPCG_PCGuidance
 * Method:    pcgIsDominated
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_JCovPCG_PCGuidance_pcgIsDominated
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     JCovPCG_PCGuidance
 * Method:    pcgIsPostDominated
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_JCovPCG_PCGuidance_pcgIsPostDominated
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
