/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JCovPCG_DynTrace */

#ifndef _Included_JCovPCG_DynTrace
#define _Included_JCovPCG_DynTrace
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JCovPCG_DynTrace
 * Method:    JvTrace
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_JCovPCG_DynTrace_JvTrace
  (JNIEnv *, jobject, jint);

/*
 * Class:     JCovPCG_DynTrace
 * Method:    JvTraceInit
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_JCovPCG_DynTrace_JvTraceInit
  (JNIEnv *, jobject, jint);

/*
 * Class:     JCovPCG_DynTrace
 * Method:    JvTraceDeInit
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_JCovPCG_DynTrace_JvTraceDeInit
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
